export const table = {
  tableShell: "relative min-h-[420px] overflow-hidden rounded-[0.875rem] border border-[color:color-mix(in_srgb,var(--native-border)_10%,transparent)] sm:min-h-[480px]",
  state: "px-4 py-12 text-center text-[var(--native-muted)]",
  overlay: "absolute inset-0 z-10 flex items-center justify-center bg-[color-mix(in_srgb,var(--native-panel)_60%,transparent)] backdrop-blur-[2px]",
  spinner: "h-8 w-8 animate-spin rounded-full border-[3px] border-[color:color-mix(in_srgb,var(--native-border)_30%,transparent)] border-t-[var(--native-primary)]",
  thead: "bg-[var(--native-bg-subtle)]",
  th: "h-auto whitespace-nowrap border-b border-[color:color-mix(in_srgb,var(--native-border)_12%,transparent)] px-3 py-[0.4375rem] text-left align-middle text-[12px] uppercase tracking-[0.04em] text-[var(--native-muted)]",
  td: "align-middle border-b border-[color:color-mix(in_srgb,var(--native-border)_8%,transparent)] px-3 py-[0.5625rem]",
  row: "cursor-pointer transition-[background-color] hover:bg-[color-mix(in_srgb,var(--native-primary)_2.5%,transparent)]",
  item: "font-semibold text-[var(--native-foreground)]",
  mut: "text-[var(--native-muted)] [font-variant-numeric:tabular-nums]",
  colCategory: "w-[9.5rem] min-w-[9.5rem]",
  colUpdated: "w-32 min-w-32",
  colAction: "w-[4.5rem] min-w-[4.5rem]",
  sort: "flex w-full items-center justify-between bg-transparent p-0 text-inherit transition-colors hover:text-[var(--native-foreground)]",
  sortOn: "text-[var(--native-foreground)]",
  sortIcon: "inline-flex flex-col items-center justify-center gap-0.5",
  sortUp: "h-0 w-0 border-l-[4px] border-r-[4px] border-b-[5px] border-l-transparent border-r-transparent border-b-[color:color-mix(in_srgb,var(--native-dim)_40%,transparent)] transition-[border-color]",
  sortUpOn: "border-b-[var(--native-primary)]",
  sortDown: "h-0 w-0 border-l-[4px] border-r-[4px] border-t-[5px] border-l-transparent border-r-transparent border-t-[color:color-mix(in_srgb,var(--native-dim)_40%,transparent)] transition-[border-color]",
  sortDownOn: "border-t-[var(--native-primary)]",
  pager: "flex flex-col gap-3 pt-4 sm:flex-row sm:items-center sm:justify-between sm:gap-4",
  pagerSum: "text-[0.8125rem] text-[var(--native-muted)]",
  pagerActs: "flex flex-wrap items-center justify-end gap-2",
  page: "inline-flex h-8 w-8 items-center justify-center rounded-[var(--native-radius-full)] border border-transparent bg-transparent text-[var(--native-muted)] transition-[background-color,color,border-color] hover:bg-[color-mix(in_srgb,var(--native-surface)_60%,transparent)] hover:text-[var(--native-foreground)] disabled:cursor-not-allowed disabled:opacity-[var(--native-disabled-opacity)]",
  pageOn: "border-[color:color-mix(in_srgb,var(--native-primary)_28%,transparent)] bg-[var(--native-primary)] text-[var(--native-primary-foreground)]",
  tshell: "overflow-hidden rounded-[var(--native-radius-md)] border border-[color:color-mix(in_srgb,var(--native-border)_20%,transparent)]",
  dt: "w-full border-collapse text-[0.8125rem] [&_thead]:bg-[var(--native-bg-subtle)] [&_th]:border-b [&_th]:border-[color:color-mix(in_srgb,var(--native-border)_12%,transparent)] [&_th]:px-3 [&_th]:py-[0.4375rem] [&_th]:text-left [&_th]:text-[12px] [&_th]:uppercase [&_th]:tracking-[0.04em] [&_th]:text-[var(--native-muted)] [&_td]:border-b [&_td]:border-[color:color-mix(in_srgb,var(--native-border)_8%,transparent)] [&_td]:px-3 [&_td]:py-[0.5625rem] [&_td]:align-middle [&_tbody_tr]:cursor-pointer [&_tbody_tr]:transition-[background-color] [&_tbody_tr:hover]:bg-[color-mix(in_srgb,var(--native-primary)_2.5%,transparent)]",
} as const