export const base = {
  section: "min-w-0",
  head: "mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between sm:gap-4",
  title: "m-0 text-[1rem] font-bold text-[var(--native-foreground)]",
  sub: "mt-0.5 text-[0.8125rem] text-[var(--native-muted)]",
  tabs: "inline-flex max-w-full flex-wrap items-center gap-1 rounded-[var(--native-radius-full)] border border-[color:color-mix(in_srgb,var(--native-border)_12%,transparent)] bg-[color-mix(in_srgb,var(--native-surface)_70%,transparent)] p-[0.1875rem]",
  tab: "inline-flex cursor-pointer items-center whitespace-nowrap rounded-[var(--native-radius-full)] border-none px-3 py-[0.3125rem] text-[0.8125rem] transition-all",
  tabOff: "bg-transparent text-[var(--native-muted)] hover:bg-[color-mix(in_srgb,var(--native-panel)_70%,transparent)] hover:text-[var(--native-primary)]",
  tabOn: "bg-[var(--native-primary)] text-[var(--native-primary-foreground)] shadow-[0_1px_4px_color-mix(in_srgb,var(--native-primary)_25%,transparent)] hover:bg-[color-mix(in_srgb,var(--native-primary)_85%,white)] hover:text-[var(--native-primary-foreground)]",
  shell: "overflow-hidden rounded-[var(--native-radius-lg)] border border-[color:color-mix(in_srgb,var(--native-border)_12%,transparent)] bg-[var(--native-panel)] p-3 shadow-[var(--native-shadow-sm)] sm:p-4",
  toolbar: "mb-3.5 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between sm:gap-4",
  toolbarTitle: "m-0 text-[0.9375rem] font-bold text-[var(--native-foreground)]",
  toolbarSub: "mt-0.5 text-[0.8125rem] text-[var(--native-muted)]",
  toolbarActs: "flex w-full flex-wrap items-center gap-1.5 sm:w-auto sm:justify-end",
  searchWrap: "relative w-full sm:w-auto",
  searchIcon: "pointer-events-none absolute left-2 top-1/2 h-[13px] w-[13px] -translate-y-1/2 text-[var(--native-dim)]",
  search: "h-[1.875rem] w-full min-w-0 rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_srgb,var(--native-border)_25%,transparent)] bg-[var(--native-panel)] pl-7 pr-2.5 text-[0.8125rem] text-[var(--native-foreground)] outline-none transition-[border-color,box-shadow] placeholder:text-[var(--native-dim)] focus:border-[var(--native-primary)] focus:shadow-[0_0_0_3px_color-mix(in_srgb,var(--native-primary)_8%,transparent)] sm:w-44",
  btn: "inline-flex h-[1.875rem] items-center justify-center gap-[0.3rem] rounded-[var(--native-radius-sm)] border border-[color:color-mix(in_srgb,var(--native-border)_25%,transparent)] bg-[var(--native-panel)] px-2.5 text-[0.8125rem] text-[var(--native-muted)] transition-all hover:border-[color:color-mix(in_srgb,var(--native-border)_45%,transparent)] hover:bg-[var(--native-bg-subtle)]",
  btnPrimary: "border-[var(--native-primary)] bg-[var(--native-primary)] text-[var(--native-primary-foreground)] hover:border-[var(--native-primary-hover)] hover:bg-[var(--native-primary-hover)]",
  badge: "inline-flex items-center rounded-[var(--native-radius-full)] bg-[var(--native-secondary)] px-2.5 py-1 text-[12px] uppercase text-[var(--native-secondary-foreground)]",
  sheet: "!p-0",
  sheetBody: "h-full max-w-none overflow-y-auto",
} as const