// This file is auto-generated by script/generate-review-builtin.ts
// Do not edit manually
// Agents are downloaded from zgsm-ai/costrict-review repository

export const BUILTIN_AGENTS = {}

export const AGENT_VERSIONS: Record<string, string> = {}
