#!/usr/bin/env bun

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const outputFile = path.resolve(__dirname, "../src/skill/builtin.ts")

// Builtin skills: name -> GitHub URL mapping
const BUILTIN_SKILLS = {
  "security-review": "https://raw.githubusercontent.com/zgsm-ai/security-review/main",
} as const

type Index = {
  skills: Array<{
    name: string
    description: string
    files: string[]
  }>
}

async function fetchIndex(url: string): Promise<Index | null> {
  const indexUrl = new URL("index.json", url.endsWith("/") ? url : `${url}/`).href
  const response = await fetch(indexUrl)
  if (!response.ok) {
    throw new Error(`Failed to fetch index: ${indexUrl} (${response.status})`)
  }
  return response.json() as Promise<Index>
}

async function fetchFile(url: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to fetch file: ${url} (${response.status})`)
  }
  return response.text()
}

async function downloadSkill(name: string, baseUrl: string): Promise<{
  name: string
  description: string
  files: Record<string, string>
}> {
  console.log(`Downloading skill: ${name} from ${baseUrl}`)

  // Fetch index.json
  const index = await fetchIndex(baseUrl)
  if (!index?.skills?.length) {
    throw new Error(`Invalid index for skill: ${name}`)
  }

  const skill = index.skills.find((s) => s.name === name)
  if (!skill) {
    throw new Error(`Skill "${name}" not found in index`)
  }

  // Download all files
  const files: Record<string, string> = {}
  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`
  const host = base.slice(0, -1)

  for (const file of skill.files) {
    const fileUrl = new URL(file, `${host}/${name}/`).href
    try {
      const content = await fetchFile(fileUrl)
      files[file] = content
      console.log(`  ✓ ${file}`)
    } catch (err) {
      console.warn(`  ✗ Failed to download ${file}: ${err}`)
      // Continue with other files
    }
  }

  // Verify SKILL.md exists
  if (!files["SKILL.md"]) {
    throw new Error(`Skill "${name}" missing SKILL.md`)
  }

  return {
    name: skill.name,
    description: skill.description,
    files,
  }
}

function escapeForTs(str: string): string {
  // Escape backticks and ${} for template literals
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
}

async function generateBuiltinSkills() {
  const imports: string[] = []
  const entries: string[] = []

  for (const [name, url] of Object.entries(BUILTIN_SKILLS)) {
    try {
      const skill = await downloadSkill(name, url)

      // Generate file entries
      const fileEntries: string[] = []
      for (const [filePath, content] of Object.entries(skill.files)) {
        const escapedContent = escapeForTs(content)
        fileEntries.push(`    "${filePath}": \`${escapedContent}\``)
      }

      entries.push(
        `  "${name}": {`,
        `    name: "${skill.name}",`,
        `    description: "${skill.description.replace(/"/g, '\\"')}",`,
        `    files: {`,
        ...fileEntries,
        `    }`,
        `  }`
      )

      console.log(`✓ Downloaded ${name} with ${Object.keys(skill.files).length} files`)
    } catch (err) {
      console.error(`✗ Failed to download skill "${name}": ${err}`)
      throw err
    }
  }

  const content = `// This file is auto-generated by script/generate-skills.ts when building the CLI
// Do not edit manually
// Generated at: ${new Date().toISOString()}

export type SkillFile = {
  name: string
  description: string
  files: Record<string, string>
}

export const BUILTIN_SKILLS: Record<string, SkillFile> = {
${entries.join(",\n")}
}

// Helper to get skill by name
export function getBuiltinSkill(name: string): SkillFile | undefined {
  return BUILTIN_SKILLS[name]
}

// List all builtin skill names
export function listBuiltinSkills(): string[] {
  return Object.keys(BUILTIN_SKILLS)
}
`

  await fs.writeFile(outputFile, content, "utf-8")
  console.log(`\nGenerated ${outputFile} with ${entries.length} builtin skills`)
}

generateBuiltinSkills().catch(console.error)
