#!/usr/bin/env bun

import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const agentDir = path.resolve(__dirname, "../src/costrict/agent")
const localesDir = path.join(agentDir, "locales")
const modelsDir = path.join(agentDir, "models")
const outputFile = path.resolve(__dirname, "../src/costrict/agent/builtin.ts")

async function scanDir(dir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true })
    return entries
      .filter((e) => e.isFile() && e.name.endsWith(".txt"))
      .map((e) => e.name)
  } catch {
    return []
  }
}

async function scanSubDirs(parentDir: string): Promise<Record<string, string[]>> {
  const result: Record<string, string[]> = {}
  try {
    const entries = await fs.readdir(parentDir, { withFileTypes: true })
    for (const entry of entries) {
      if (entry.isDirectory()) {
        result[entry.name] = await scanDir(path.join(parentDir, entry.name))
      }
    }
  } catch {
    // directory doesn't exist
  }
  return result
}

async function generateBuiltinAgents() {
  // Scan locales/{locale}/*.txt
  const localeFiles = await scanSubDirs(localesDir)
  // Scan models/{family}/*.txt
  const modelFiles = await scanSubDirs(modelsDir)

  // Collect all unique agent filenames across all locales
  const allNames = new Set<string>()
  for (const files of Object.values(localeFiles)) {
    for (const f of files) allNames.add(f)
  }

  const imports: string[] = []
  const entries: string[] = []
  let idx = 0

  for (const name of [...allNames].sort()) {
    const localeImports: string[] = []
    const modelImports: string[] = []

    // Locale imports
    const localeEntries: string[] = []
    for (const [locale, files] of Object.entries(localeFiles)) {
      if (!files.includes(name)) continue
      const varName = `AGENT_${idx++}`
      const rel = path.relative(path.dirname(outputFile), path.join(localesDir, locale, name)).replaceAll("\\", "/")
      imports.push(`import ${varName} from "./${rel}"`)
      localeEntries.push(`"${locale}": ${varName}`)
      localeImports.push(varName)
    }

    // Model imports
    const modelEntries: string[] = []
    for (const [family, files] of Object.entries(modelFiles)) {
      if (!files.includes(name)) continue
      const varName = `AGENT_${idx++}`
      const rel = path.relative(path.dirname(outputFile), path.join(modelsDir, family, name)).replaceAll("\\", "/")
      imports.push(`import ${varName} from "./${rel}"`)
      modelEntries.push(`"${family}": ${varName}`)
      modelImports.push(varName)
    }

    const stem = name.replace(/\.txt$/, "")
    const localesObj = `locales: { ${localeEntries.join(", ")} }`
    const modelsObj = modelEntries.length > 0 ? `, models: { ${modelEntries.join(", ")} }` : ""
    entries.push(`  "${stem}": { ${localesObj}${modelsObj} }`)
  }

  const content = `// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

${imports.join("\n")}

export type AgentEntry = {
  locales: Record<string, string>
  models?: Record<string, string>
}

export const BUILTIN_AGENTS: Record<string, AgentEntry> = {
${entries.join(",\n")}
}
`

  await fs.writeFile(outputFile, content, "utf-8")
  const localeCount = Object.keys(localeFiles).length
  const agentCount = allNames.size
  console.log(`Generated ${outputFile} with ${agentCount} agents across ${localeCount} locales`)
}

generateBuiltinAgents().catch(console.error)
