// This file is auto-generated by script/generate-review-builtin.ts
// Do not edit manually

export const BUILTIN_AGENTS: Record<string, {
  agentType: string
  whenToUse: string
  tools: string[]
  color: string
  model: string
  permissionMode: string
  getSystemPrompt: () => string
  source: "built-in"
  baseDir: "built-in"
}> = {}

export const AGENT_VERSIONS: Record<string, string> = {}
