// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

import AGENT_0 from "./01-wiki-project-analyze.txt"
import AGENT_1 from "./02-wiki-catalogue-design.txt"
import AGENT_2 from "./03-wiki-document-generate.txt"
import AGENT_3 from "./04-wiki-index-generation.txt"
import AGENT_4 from "./architect.txt"
import AGENT_5 from "./coding.txt"
import AGENT_6 from "./fix-agent.txt"
import AGENT_7 from "./quick-explore.txt"
import AGENT_8 from "./requirements.txt"
import AGENT_9 from "./spec-apply.txt"
import AGENT_10 from "./strict-plan.txt"
import AGENT_11 from "./strict-spec.txt"
import AGENT_12 from "./sub-coding.txt"
import AGENT_13 from "./task-check.txt"
import AGENT_14 from "./task.txt"
import AGENT_15 from "./tdd.txt"

export const BUILTIN_AGENTS = [
  AGENT_0,
  AGENT_1,
  AGENT_2,
  AGENT_3,
  AGENT_4,
  AGENT_5,
  AGENT_6,
  AGENT_7,
  AGENT_8,
  AGENT_9,
  AGENT_10,
  AGENT_11,
  AGENT_12,
  AGENT_13,
  AGENT_14,
  AGENT_15
]
