// This file is auto-generated by script/generate-agents.ts when building the CLI
// Do not edit manually

import AGENT_0 from "./locales/zh-CN/01-wiki-project-analyze.txt"
import AGENT_1 from "./locales/en/01-wiki-project-analyze.txt"
import AGENT_2 from "./locales/zh-CN/02-wiki-catalogue-design.txt"
import AGENT_3 from "./locales/en/02-wiki-catalogue-design.txt"
import AGENT_4 from "./locales/zh-CN/03-wiki-document-generate.txt"
import AGENT_5 from "./locales/en/03-wiki-document-generate.txt"
import AGENT_6 from "./locales/zh-CN/04-wiki-index-generation.txt"
import AGENT_7 from "./locales/en/04-wiki-index-generation.txt"
import AGENT_8 from "./locales/zh-CN/plan-apply.txt"
import AGENT_9 from "./locales/en/plan-apply.txt"
import AGENT_10 from "./locales/zh-CN/plan-fix-agent.txt"
import AGENT_11 from "./locales/en/plan-fix-agent.txt"
import AGENT_12 from "./locales/zh-CN/plan-quick-explore.txt"
import AGENT_13 from "./locales/en/plan-quick-explore.txt"
import AGENT_14 from "./locales/zh-CN/plan-sub-coding.txt"
import AGENT_15 from "./locales/en/plan-sub-coding.txt"
import AGENT_16 from "./locales/zh-CN/plan-task-check.txt"
import AGENT_17 from "./locales/en/plan-task-check.txt"
import AGENT_18 from "./locales/zh-CN/spec-design.txt"
import AGENT_19 from "./locales/en/spec-design.txt"
import AGENT_20 from "./locales/zh-CN/spec-plan-manager.txt"
import AGENT_21 from "./locales/en/spec-plan-manager.txt"
import AGENT_22 from "./locales/zh-CN/spec-plan.txt"
import AGENT_23 from "./locales/en/spec-plan.txt"
import AGENT_24 from "./locales/zh-CN/spec-requirement.txt"
import AGENT_25 from "./locales/en/spec-requirement.txt"
import AGENT_26 from "./locales/zh-CN/spec-task.txt"
import AGENT_27 from "./locales/en/spec-task.txt"
import AGENT_28 from "./locales/zh-CN/strict-plan.txt"
import AGENT_29 from "./locales/en/strict-plan.txt"
import AGENT_30 from "./locales/zh-CN/strict-spec.txt"
import AGENT_31 from "./locales/en/strict-spec.txt"
import AGENT_32 from "./locales/zh-CN/tdd.txt"
import AGENT_33 from "./locales/en/tdd.txt"

export type AgentEntry = {
  locales: Record<string, string>
  models?: Record<string, string>
}

export const BUILTIN_AGENTS: Record<string, AgentEntry> = {
  "01-wiki-project-analyze": { locales: { "zh-CN": AGENT_0, "en": AGENT_1 } },
  "02-wiki-catalogue-design": { locales: { "zh-CN": AGENT_2, "en": AGENT_3 } },
  "03-wiki-document-generate": { locales: { "zh-CN": AGENT_4, "en": AGENT_5 } },
  "04-wiki-index-generation": { locales: { "zh-CN": AGENT_6, "en": AGENT_7 } },
  "plan-apply": { locales: { "zh-CN": AGENT_8, "en": AGENT_9 } },
  "plan-fix-agent": { locales: { "zh-CN": AGENT_10, "en": AGENT_11 } },
  "plan-quick-explore": { locales: { "zh-CN": AGENT_12, "en": AGENT_13 } },
  "plan-sub-coding": { locales: { "zh-CN": AGENT_14, "en": AGENT_15 } },
  "plan-task-check": { locales: { "zh-CN": AGENT_16, "en": AGENT_17 } },
  "spec-design": { locales: { "zh-CN": AGENT_18, "en": AGENT_19 } },
  "spec-plan-manager": { locales: { "zh-CN": AGENT_20, "en": AGENT_21 } },
  "spec-plan": { locales: { "zh-CN": AGENT_22, "en": AGENT_23 } },
  "spec-requirement": { locales: { "zh-CN": AGENT_24, "en": AGENT_25 } },
  "spec-task": { locales: { "zh-CN": AGENT_26, "en": AGENT_27 } },
  "strict-plan": { locales: { "zh-CN": AGENT_28, "en": AGENT_29 } },
  "strict-spec": { locales: { "zh-CN": AGENT_30, "en": AGENT_31 } },
  "tdd": { locales: { "zh-CN": AGENT_32, "en": AGENT_33 } }
}
