// This file is auto-generated by script/generate-skills.ts when building the CLI
// Do not edit manually

export type SkillFile = {
  name: string
  description: string
  files: Record<string, string>
}

export const BUILTIN_SKILLS: Record<string, SkillFile> = {}

// Helper to get skill by name
export function getBuiltinSkill(name: string): SkillFile | undefined {
  return BUILTIN_SKILLS[name]
}

// List all builtin skill names
export function listBuiltinSkills(): string[] {
  return Object.keys(BUILTIN_SKILLS)
}
