// This file is auto-generated by script/generate-review-builtin.ts
// Do not edit manually
// All skill and agent files are embedded at build time for compiled builds

export const BUNDLED_SKILLS: Record<string, Record<string, string>> = {}

export async function loadSkillFiles(skillName: string): Promise<Record<string, string>> {
  return BUNDLED_SKILLS[skillName] || {}
}

export async function listSkillFiles(skillName: string): Promise<string[]> {
  return Object.keys(BUNDLED_SKILLS[skillName] || {})
}

export async function loadSkillFile(skillName: string, filePath: string): Promise<string> {
  const skillFiles = BUNDLED_SKILLS[skillName]
  if (!skillFiles) {
    throw new Error(`Skill not found: ${skillName}`)
  }
  const content = skillFiles[filePath]
  if (content === undefined) {
    throw new Error(`File not found in skill ${skillName}: ${filePath}`)
  }
  return content
}

export async function getBuiltinSkillVersion(skillName: string): Promise<string | undefined> {
  return undefined
}

export async function getAllBuiltinSkillVersions(): Promise<Record<string, string>> {
  return {}
}

export function listBuiltinSkills(): string[] {
  return []
}

export function isBuiltinSkill(name: string): boolean {
  return false
}

export async function extractBundledSkill(skillName: string, targetDir: string): Promise<void> {
  throw new Error(`Skill not found: ${skillName}`)
}
