// This file is auto-generated by script/generate-skills.ts
// Do not edit manually

import { readFile } from "fs/promises"
import { join } from "path"
import { fileURLToPath } from "url"
import { dirname } from "path"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Get the bundled skills directory (relative to this file)
 */
function getBundledSkillsDir(): string {
  // Navigate from src/costrict/skill/ to bundled-skills/
  return join(__dirname, "../../../bundled-skills")
}

/**
 * Load skill metadata from index.json
 */
async function loadIndex(): Promise<{
  version: string
  skills: Array<{ name: string; commitSha: string }>
} | null> {
  try {
    const indexPath = join(getBundledSkillsDir(), "index.json")
    const content = await readFile(indexPath, "utf-8")
    return JSON.parse(content)
  } catch {
    return null
  }
}

/**
 * Load a single skill file content
 */
export async function loadSkillFile(skillName: string, filePath: string): Promise<string> {
  const skillDir = join(getBundledSkillsDir(), skillName)
  const fullPath = join(skillDir, filePath)
  const content = await readFile(fullPath, "utf-8")
  return content
}

/**
 * Get all files in a skill directory
 */
export async function listSkillFiles(skillName: string): Promise<string[]> {
  const { readdir } = await import("fs/promises")
  const { join } = await import("path")
  const skillDir = join(getBundledSkillsDir(), skillName)

  async function walk(dir: string, base = ""): Promise<string[]> {
    const entries = await readdir(dir, { withFileTypes: true })
    const files: string[] = []

    for (const entry of entries) {
      const fullPath = join(dir, entry.name)
      const relativePath = base ? join(base, entry.name) : entry.name

      if (entry.isDirectory()) {
        files.push(...await walk(fullPath, relativePath))
      } else {
        files.push(relativePath)
      }
    }

    return files
  }

  return walk(skillDir)
}

/**
 * Load all files for a skill as a Record<string, string>
 */
export async function loadSkillFiles(skillName: string): Promise<Record<string, string>> {
  const files = await listSkillFiles(skillName)
  const result: Record<string, string> = {}

  for (const file of files) {
    result[file] = await loadSkillFile(skillName, file)
  }

  return result
}

/**
 * Get the version (commit SHA) for a specific builtin skill
 */
export async function getBuiltinSkillVersion(skillName: string): Promise<string | undefined> {
  const index = await loadIndex()
  return index?.skills.find(s => s.name === skillName)?.commitSha
}

/**
 * Get all builtin skill versions
 */
export async function getAllBuiltinSkillVersions(): Promise<Record<string, string>> {
  const index = await loadIndex()
  const result: Record<string, string> = {}

  if (index) {
    for (const skill of index.skills) {
      result[skill.name] = skill.commitSha
    }
  }

  return result
}

/**
 * List all builtin skill names
 */
export function listBuiltinSkills(): string[] {
  return ["security-review"]
}

/**
 * Check if a skill is a builtin skill
 */
export function isBuiltinSkill(name: string): boolean {
  return ["security-review"].includes(name)
}
