// This file is auto-generated by script/generate-review-builtin.ts
// Do not edit manually

export const SKILL_FILES: Record<string, Record<string, string>> = {}

const SKILL_VERSIONS: Record<string, string> = {}

export function listBuiltinSkills(): string[] {
  return []
}

export function getBuiltinSkillVersion(skillName: string): string | undefined {
  return SKILL_VERSIONS[skillName]
}

export function listSkillFiles(skillName: string, locale: string): string[] {
  return Object.keys(SKILL_FILES[locale]?.[skillName] || {})
}

export async function extractBundledSkill(skillName: string, targetDir: string, locale: string): Promise<void> {
  throw new Error(`Skill not found: ${skillName}`)
}
