name: release
run-name: "${{ format('release {0}', inputs.bump) }}"

on:
  push:
    branches:
      - ci
      - dev
      - beta
      - snapshot-*
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump major, minor, or patch"
        required: false
        type: choice
        options:
          - major
          - minor
          - patch
      version:
        description: "Override version (optional)"
        required: false
        type: string

concurrency: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.version || inputs.bump }}

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  version:
    runs-on: ubuntu-latest
    if: github.repository == 'zgsm-ai/opencode'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-bun

      - name: Setup git committer
        id: committer
        uses: ./.github/actions/setup-git-committer
        with:
          opencode-app-id: ${{ vars.OPENCODE_APP_ID }}
          opencode-app-secret: ${{ secrets.OPENCODE_APP_SECRET }}

      - name: Install OpenCode
        if: inputs.bump || inputs.version
        run: bun i -g opencode-ai

      - id: version
        run: |
          ./script/version.ts
        env:
          GH_TOKEN: ${{ steps.committer.outputs.token }}
          OPENCODE_BUMP: ${{ inputs.bump }}
          OPENCODE_VERSION: ${{ inputs.version }}
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GH_REPO: ${{ (github.ref_name == 'beta' && 'zgsm-ai/opencode-beta') || github.repository }}
    outputs:
      version: ${{ steps.version.outputs.version }}
      release: ${{ steps.version.outputs.release }}
      tag: ${{ steps.version.outputs.tag }}
      repo: ${{ steps.version.outputs.repo }}

  build:
    needs: version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.version }}
      release: ${{ needs.version.outputs.release }}
      tag: ${{ needs.version.outputs.tag }}
      repo: ${{ needs.version.outputs.repo }}
    secrets: inherit

  publish:
    needs:
      - version
      - build
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ needs.version.outputs.version }}
      release: ${{ needs.version.outputs.release }}
      repo: ${{ needs.version.outputs.repo }}
    secrets: inherit
